//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAPICodePack.ShellExtensions.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnhanceForm.Microsoft.WindowsAPICodePack.ShellExtensions.Resources.LocalizedMessa" +
                            "ges", typeof(LocalizedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Control has not yet been assigned. Methods requiring it cannot be called. ähnelt.
        /// </summary>
        internal static string PreviewHandlerControlNotInitialized {
            get {
                return ResourceManager.GetString("PreviewHandlerControlNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} must implement one or more of IPreviewFromStream, IPreviewFromShellObject or IPreviewFromFile. ähnelt.
        /// </summary>
        internal static string PreviewHandlerInterfaceNotImplemented {
            get {
                return ResourceManager.GetString("PreviewHandlerInterfaceNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PreviewHandler &apos;{0}&apos; must have exactly one PreviewHandler attribute. ähnelt.
        /// </summary>
        internal static string PreviewHandlerInvalidAttributes {
            get {
                return ResourceManager.GetString("PreviewHandlerInvalidAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to call interface {0} because it is not supported on this object. ähnelt.
        /// </summary>
        internal static string PreviewHandlerUnsupportedInterfaceCalled {
            get {
                return ResourceManager.GetString("PreviewHandlerUnsupportedInterfaceCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sum of offset and count must be less than or equal to the size of the buffer. ähnelt.
        /// </summary>
        internal static string StorageStreamBufferOverflow {
            get {
                return ResourceManager.GetString("StorageStreamBufferOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count must be greater than or equal to zero. ähnelt.
        /// </summary>
        internal static string StorageStreamCountLessThanZero {
            get {
                return ResourceManager.GetString("StorageStreamCountLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The stream was initialized as read-only. ähnelt.
        /// </summary>
        internal static string StorageStreamIsReadonly {
            get {
                return ResourceManager.GetString("StorageStreamIsReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset must be greater than or equal to zero. ähnelt.
        /// </summary>
        internal static string StorageStreamOffsetLessThanZero {
            get {
                return ResourceManager.GetString("StorageStreamOffsetLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} does not implement IThumbnailFromStream and so requires DisableProcessIsolation set to true. ähnelt.
        /// </summary>
        internal static string ThumbnailProviderDisabledProcessIsolation {
            get {
                return ResourceManager.GetString("ThumbnailProviderDisabledProcessIsolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} must implement one or more of IThumbnailFromStream, IThumbnailFromShellObject or IThumbnailFromFile. ähnelt.
        /// </summary>
        internal static string ThumbnailProviderInterfaceNotImplemented {
            get {
                return ResourceManager.GetString("ThumbnailProviderInterfaceNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot retrieve handle because proxy window has not been created. ähnelt.
        /// </summary>
        internal static string WpfPreviewHandlerNoHandle {
            get {
                return ResourceManager.GetString("WpfPreviewHandlerNoHandle", resourceCulture);
            }
        }
    }
}
